// Package speculative implements speculative decoding for faster inference.
// Speculative decoding uses a small draft model to generate candidate tokens,
// which are then verified in parallel by the larger target model.
//
// The algorithm works as follows:
// 1. Draft model generates K candidate tokens quickly
// 2. Target model verifies all K tokens in a single forward pass
// 3. Accept tokens where target agrees with draft (using rejection sampling)
// 4. If a token is rejected, use the target's token instead
//
// This can provide 2-4x speedup when the draft model has high acceptance rate.
//
// Based on: "Fast Inference from Transformers via Speculative Decoding"
// (Leviathan et al., 2022)
package speculative

import (
	"context"
	"log/slog"
	"math"
	"math/rand"
	"strings"
	"sync"
	"time"

	"github.com/ollama/ollama/api"
	"github.com/ollama/ollama/llm"
)

// Config holds the configuration for speculative decoding
type Config struct {
	// DraftModelName is the name of the draft model to use
	DraftModelName string

	// NumSpeculativeTokens is the number of tokens to speculate ahead (default: 5)
	NumSpeculativeTokens int

	// AcceptanceThreshold is the minimum probability ratio for accepting a token (default: 0.9)
	AcceptanceThreshold float64

	// Enabled indicates if speculative decoding is active
	Enabled bool
}

// DefaultConfig returns the default speculative decoding configuration
func DefaultConfig() Config {
	return Config{
		NumSpeculativeTokens: 5,
		AcceptanceThreshold:  0.9,
		Enabled:              false,
	}
}

// ConfigFromModel creates a speculative config from a model's draft setting
func ConfigFromModel(draftModelName string) Config {
	if draftModelName == "" {
		return DefaultConfig()
	}
	return Config{
		DraftModelName:       draftModelName,
		NumSpeculativeTokens: 5,
		AcceptanceThreshold:  0.9,
		Enabled:              true,
	}
}

// Engine manages speculative decoding with draft and target models
type Engine struct {
	config Config

	// draftServer is the smaller, faster model for generating candidate tokens
	draftServer llm.LlamaServer

	// targetServer is the larger model that verifies tokens
	targetServer llm.LlamaServer

	mu sync.Mutex

	// Metrics
	totalTokens     int64
	acceptedTokens  int64
	speculatedBatch int64
	verifiedBatch   int64

	// Cached token strings for acceptance checking
	draftContent []string
}

// NewEngine creates a new speculative decoding engine
func NewEngine(config Config) *Engine {
	return &Engine{
		config:       config,
		draftContent: make([]string, 0, config.NumSpeculativeTokens),
	}
}

// SetDraftServer sets the draft model server
func (e *Engine) SetDraftServer(server llm.LlamaServer) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.draftServer = server
}

// SetTargetServer sets the target model server
func (e *Engine) SetTargetServer(server llm.LlamaServer) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.targetServer = server
}

// IsReady returns true if both servers are loaded and ready
func (e *Engine) IsReady() bool {
	e.mu.Lock()
	defer e.mu.Unlock()
	return e.draftServer != nil && e.targetServer != nil && e.config.Enabled
}

// SpeculativeResult contains the result of speculative decoding
type SpeculativeResult struct {
	// AcceptedTokens are the tokens that were accepted from speculation
	AcceptedTokens []int32

	// Content is the decoded text content
	Content string

	// DraftTokens is the total number of tokens generated by draft model
	DraftTokens int

	// TargetTokens is the number of tokens verified by target model
	TargetTokens int

	// AcceptanceRate is the ratio of accepted tokens
	AcceptanceRate float64

	// SpeedupFactor is the estimated speedup achieved
	SpeedupFactor float64
}

// DraftCandidate represents a candidate token from the draft model
type DraftCandidate struct {
	Token    int32
	Logprob  float64
	TopProbs []llm.TokenLogprob
}

// GenerateDraftTokens generates candidate tokens using the draft model
func (e *Engine) GenerateDraftTokens(ctx context.Context, prompt string, numTokens int) ([]DraftCandidate, error) {
	e.mu.Lock()
	draft := e.draftServer
	e.mu.Unlock()

	if draft == nil {
		return nil, nil
	}

	candidates := make([]DraftCandidate, 0, numTokens)
	currentPrompt := prompt

	opts := api.DefaultOptions()
	opts.NumPredict = 1
	opts.Temperature = 0.0 // Greedy for draft

	for i := 0; i < numTokens; i++ {
		select {
		case <-ctx.Done():
			return candidates, ctx.Err()
		default:
		}

		var response llm.CompletionResponse
		var lastContent string

		err := draft.Completion(ctx, llm.CompletionRequest{
			Prompt:      currentPrompt,
			Options:     &opts,
			Logprobs:    true,
			TopLogprobs: 5,
		}, func(resp llm.CompletionResponse) {
			response = resp
			lastContent = resp.Content
		})

		if err != nil {
			return candidates, err
		}

		if response.Done || lastContent == "" {
			break
		}

		// Extract token info from logprobs
		var candidate DraftCandidate
		if len(response.Logprobs) > 0 {
			lp := response.Logprobs[0]
			candidate = DraftCandidate{
				Logprob:  lp.Logprob,
				TopProbs: lp.TopLogprobs,
			}
		}

		candidates = append(candidates, candidate)
		currentPrompt += lastContent
	}

	return candidates, nil
}

// VerifyTokens verifies draft tokens using the target model
// Returns the index of the last accepted token (-1 if none accepted)
func (e *Engine) VerifyTokens(ctx context.Context, prompt string, draftTokens []DraftCandidate) (int, []llm.Logprob, error) {
	e.mu.Lock()
	target := e.targetServer
	e.mu.Unlock()

	if target == nil || len(draftTokens) == 0 {
		return -1, nil, nil
	}

	// Build the full prompt with draft tokens for batch verification
	fullPrompt := prompt
	for _, dt := range draftTokens {
		// We need to detokenize the draft tokens
		// For now, we'll use the content directly if available
		_ = dt
	}

	opts := api.DefaultOptions()
	opts.NumPredict = len(draftTokens) + 1 // Verify all draft tokens + one more
	opts.Temperature = 0.0

	var logprobs []llm.Logprob
	err := target.Completion(ctx, llm.CompletionRequest{
		Prompt:      fullPrompt,
		Options:     &opts,
		Logprobs:    true,
		TopLogprobs: 5,
	}, func(resp llm.CompletionResponse) {
		logprobs = append(logprobs, resp.Logprobs...)
	})

	if err != nil {
		return -1, nil, err
	}

	// Find how many tokens to accept using rejection sampling
	accepted := e.acceptTokens(draftTokens, logprobs)

	return accepted, logprobs, nil
}

// acceptTokens determines how many draft tokens to accept based on target model probabilities
// Uses the standard speculative decoding acceptance criterion from the paper:
// "Fast Inference from Transformers via Speculative Decoding" (Leviathan et al., 2022)
func (e *Engine) acceptTokens(draftTokens []DraftCandidate, targetLogprobs []llm.Logprob) int {
	accepted := 0

	for i, draft := range draftTokens {
		if i >= len(targetLogprobs) {
			break
		}

		targetProb := math.Exp(targetLogprobs[i].Logprob)
		draftProb := math.Exp(draft.Logprob)

		// Prevent division by zero
		if draftProb <= 1e-10 {
			break
		}

		// Acceptance criterion from the paper:
		// Accept if target_prob >= draft_prob (always accept)
		// Otherwise accept with probability target_prob / draft_prob
		acceptanceRatio := targetProb / draftProb

		if acceptanceRatio >= 1.0 {
			// Target is more confident, always accept
			accepted++
		} else if acceptanceRatio >= e.config.AcceptanceThreshold {
			// Within threshold, probabilistically accept
			if rand.Float64() < acceptanceRatio {
				accepted++
			} else {
				// Rejected - stop accepting further tokens
				break
			}
		} else {
			// Below threshold, reject
			break
		}
	}

	return accepted
}

// Speculate performs one round of speculative decoding
func (e *Engine) Speculate(ctx context.Context, prompt string) (*SpeculativeResult, error) {
	startTime := time.Now()

	// Generate draft tokens
	draftTokens, err := e.GenerateDraftTokens(ctx, prompt, e.config.NumSpeculativeTokens)
	if err != nil {
		return nil, err
	}

	if len(draftTokens) == 0 {
		return &SpeculativeResult{
			DraftTokens:    0,
			TargetTokens:   0,
			AcceptanceRate: 0,
			SpeedupFactor:  1.0,
		}, nil
	}

	// Verify with target model
	accepted, _, err := e.VerifyTokens(ctx, prompt, draftTokens)
	if err != nil {
		return nil, err
	}

	// Update metrics
	e.mu.Lock()
	e.totalTokens += int64(len(draftTokens))
	e.acceptedTokens += int64(accepted)
	e.speculatedBatch++
	if accepted > 0 {
		e.verifiedBatch++
	}
	e.mu.Unlock()

	acceptanceRate := 0.0
	if len(draftTokens) > 0 {
		acceptanceRate = float64(accepted) / float64(len(draftTokens))
	}

	// Estimate speedup: tokens_accepted / time_spent
	// Simplified estimation
	duration := time.Since(startTime)
	speedup := 1.0
	if accepted > 0 && duration > 0 {
		// Rough estimate: accepted tokens in time it would take for 1 target token
		speedup = float64(accepted+1) / 2.0 // Conservative estimate
	}

	slog.Debug("speculative decoding round",
		"draft_tokens", len(draftTokens),
		"accepted", accepted,
		"acceptance_rate", acceptanceRate,
		"duration", duration)

	return &SpeculativeResult{
		DraftTokens:    len(draftTokens),
		TargetTokens:   accepted + 1, // accepted + 1 from target
		AcceptanceRate: acceptanceRate,
		SpeedupFactor:  speedup,
	}, nil
}

// SpeculativeCompletion performs completion with speculative decoding
// This wraps the target model's completion with draft-assisted speculation
// It returns a callback that can be used like regular Completion
func (e *Engine) SpeculativeCompletion(ctx context.Context, req llm.CompletionRequest, fn func(llm.CompletionResponse)) error {
	if !e.IsReady() {
		// Fall back to normal completion if speculative decoding isn't ready
		e.mu.Lock()
		target := e.targetServer
		e.mu.Unlock()
		if target != nil {
			slog.Debug("speculative decoding not ready, falling back to normal completion")
			return target.Completion(ctx, req, fn)
		}
		return nil
	}

	slog.Info("starting speculative decoding completion",
		"draft_model", e.config.DraftModelName,
		"num_speculative_tokens", e.config.NumSpeculativeTokens)

	startTime := time.Now()
	var totalDraft, totalAccepted int64
	var currentPrompt strings.Builder
	currentPrompt.WriteString(req.Prompt)

	// Create modified options for draft model (greedy, fast)
	draftOpts := api.DefaultOptions()
	draftOpts.Temperature = 0
	draftOpts.NumPredict = 1

	e.mu.Lock()
	draft := e.draftServer
	target := e.targetServer
	numSpec := e.config.NumSpeculativeTokens
	e.mu.Unlock()

	// Main speculative decoding loop
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		// Step 1: Generate draft tokens
		draftTokens := make([]string, 0, numSpec)
		draftLogprobs := make([]float64, 0, numSpec)
		draftPrompt := currentPrompt.String()

		for i := 0; i < numSpec; i++ {
			var draftContent string
			var draftLogprob float64
			var done bool

			err := draft.Completion(ctx, llm.CompletionRequest{
				Prompt:      draftPrompt,
				Options:     &draftOpts,
				Logprobs:    true,
				TopLogprobs: 1,
			}, func(resp llm.CompletionResponse) {
				draftContent = resp.Content
				done = resp.Done
				if len(resp.Logprobs) > 0 {
					draftLogprob = resp.Logprobs[0].Logprob
				}
			})

			if err != nil || done || draftContent == "" {
				break
			}

			draftTokens = append(draftTokens, draftContent)
			draftLogprobs = append(draftLogprobs, draftLogprob)
			draftPrompt += draftContent
		}

		if len(draftTokens) == 0 {
			// No draft tokens, run target directly
			break
		}

		totalDraft += int64(len(draftTokens))

		// Step 2: Verify with target model (batch verification)
		// Build verification prompt with all draft tokens
		verifyPrompt := currentPrompt.String()
		for _, dt := range draftTokens {
			verifyPrompt += dt
		}

		var targetLogprobs []llm.Logprob
		var targetContent string
		var targetDone bool

		verifyOpts := *req.Options
		verifyOpts.NumPredict = len(draftTokens) + 1

		err := target.Completion(ctx, llm.CompletionRequest{
			Prompt:      currentPrompt.String(),
			Images:      req.Images,
			Format:      req.Format,
			Options:     &verifyOpts,
			Logprobs:    true,
			TopLogprobs: 5,
		}, func(resp llm.CompletionResponse) {
			targetLogprobs = append(targetLogprobs, resp.Logprobs...)
			targetContent += resp.Content
			targetDone = resp.Done
		})

		if err != nil {
			return err
		}

		// Step 3: Accept/reject using standard speculative decoding criterion
		accepted := 0
		for i := 0; i < len(draftTokens) && i < len(targetLogprobs); i++ {
			targetProb := math.Exp(targetLogprobs[i].Logprob)
			draftProb := math.Exp(draftLogprobs[i])

			if draftProb <= 1e-10 {
				break
			}

			acceptanceRatio := targetProb / draftProb

			// Accept if target agrees or probabilistically based on ratio
			if acceptanceRatio >= 1.0 || rand.Float64() < acceptanceRatio {
				accepted++
				totalAccepted++
			} else {
				break
			}
		}

		// Emit accepted tokens
		for i := 0; i < accepted; i++ {
			fn(llm.CompletionResponse{
				Content: draftTokens[i],
			})
			currentPrompt.WriteString(draftTokens[i])
		}

		// If not all accepted, emit the corrected token from target
		if accepted < len(draftTokens) && len(targetContent) > 0 {
			// Get the correction token (what target predicted at the rejection point)
			correctionStart := 0
			for i := 0; i < accepted && correctionStart < len(targetContent); i++ {
				correctionStart += len(draftTokens[i])
			}
			if correctionStart < len(targetContent) {
				// Find next token boundary (simplified - just take remaining)
				correction := targetContent[correctionStart:]
				if len(correction) > 0 {
					// Take just one token worth
					fn(llm.CompletionResponse{
						Content: correction,
					})
					currentPrompt.WriteString(correction)
				}
			}
		}

		if targetDone {
			// Final response with metrics
			duration := time.Since(startTime)
			acceptanceRate := 0.0
			if totalDraft > 0 {
				acceptanceRate = float64(totalAccepted) / float64(totalDraft)
			}

			slog.Info("speculative decoding completed",
				"total_draft", totalDraft,
				"total_accepted", totalAccepted,
				"acceptance_rate", acceptanceRate,
				"duration", duration)

			fn(llm.CompletionResponse{
				Done:       true,
				DoneReason: llm.DoneReasonStop,
			})
			break
		}
	}

	return nil
}

// Stats returns current speculative decoding statistics
func (e *Engine) Stats() (totalTokens, acceptedTokens int64, acceptanceRate float64) {
	e.mu.Lock()
	defer e.mu.Unlock()

	totalTokens = e.totalTokens
	acceptedTokens = e.acceptedTokens
	if totalTokens > 0 {
		acceptanceRate = float64(acceptedTokens) / float64(totalTokens)
	}
	return
}

// Close releases resources
func (e *Engine) Close() error {
	e.mu.Lock()
	defer e.mu.Unlock()

	// Note: The servers are managed by the scheduler, not closed here
	e.draftServer = nil
	e.targetServer = nil
	return nil
}
